### ISSUE TITLE
ERROR Plugin load failed

### ISSUE THREAD

**Issue by scabbarddii** [knksmith57/hexo-renderer-sass#13]
When I run `hexo --version`

```
ERROR Plugin load failed: hexo-renderer-sass
Error: dlopen(/Users/Scabbard/Documents/Github/scabbarddii.github.io/node_modules/node-sass/vendor/darwin-x64-48/binding.node, 1): no suitable image found.  Did find:
    /Users/Scabbard/Documents/Github/scabbarddii.github.io/node_modules/node-sass/vendor/darwin-x64-48/binding.node: truncated mach-o error: segment __TEXT extends to 1212416 which is past end of file 43963
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Scabbard/Documents/Github/scabbarddii.github.io/node_modules/node-sass/lib/index.js:24:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (/Users/Scabbard/Documents/Github/scabbarddii.github.io/node_modules/hexo/lib/hexo/index.js:213:21)
    at /Users/Scabbard/Documents/Github/scabbarddii.github.io/node_modules/hexo-renderer-sass/index.js:1:79
    at /Users/Scabbard/Documents/Github/scabbarddii.github.io/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/Users/Scabbard/Documents/Github/scabbarddii.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Scabbard/Documents/Github/scabbarddii.github.io/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/Scabbard/Documents/Github/scabbarddii.github.io/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/Scabbard/Documents/Github/scabbarddii.github.io/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/Scabbard/Documents/Github/scabbarddii.github.io/node_modules/bluebird/js/release/promise.js:685:18)
```

And I'm using:

```
hexo: 3.2.2
hexo-cli: 1.0.2
os: Darwin 15.5.0 darwin x64
http_parser: 2.7.0
node: 6.2.2
v8: 5.0.71.52
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
```

Thanks for the help.

**Comment by JLHwung** [comment]
Please run `npm rebuild`.

**Comment by JLHwung** [comment]
Closed without reply after 14 days. Will re-open if replied.

**Comment by Yin-Hongwei** [comment]
1.npm install -g cnpm --registry=https://registry.npm.taobao.org
2.cnpm install node-sass@latest
