### ISSUE TITLE
node-sass@3.13.1 linux-x64-57 doesn't exist

### ISSUE THREAD

**Issue by noraj1337** [knksmith57/hexo-renderer-sass#36]
In `node-sass@3.13.1` the release `linux-x64-57` doesn't exist but `linux-x64-51` does. So the HTTP request get a 404 error.

```
npm install hexo-render-sass --save                                                                                                                                             noraj@manji
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> node-sass@4.5.3 install /tmp/Rawsec/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-57_binding.node
Download complete  ] - :
Binary saved to /tmp/Rawsec/node_modules/node-sass/vendor/linux-x64-57/binding.node
Caching binary to /home/noraj/.npm/node-sass/4.5.3/linux-x64-57_binding.node

> node-sass@3.13.1 install /tmp/Rawsec/node_modules/hexo-renderer-sass/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.5.3 postinstall /tmp/Rawsec/node_modules/node-sass
> node scripts/build.js

Binary found at /tmp/Rawsec/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine

> node-sass@3.13.1 postinstall /tmp/Rawsec/node_modules/hexo-renderer-sass/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /tmp/Rawsec/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/tmp/Rawsec/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.1.2 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.13\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.1.2
gyp verb command install [ '8.1.2' ]
gyp verb install input version string "8.1.2"
gyp verb install installing version: 8.1.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.1.2
gyp verb build dir attempting to create "build" dir: /tmp/Rawsec/node_modules/hexo-renderer-sass/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /tmp/Rawsec/node_modules/hexo-renderer-sass/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /tmp/Rawsec/node_modules/hexo-renderer-sass/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /tmp/Rawsec/node_modules/hexo-renderer-sass/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /tmp/Rawsec/node_modules/hexo-renderer-sass/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/tmp/Rawsec/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/Rawsec/node_modules/hexo-renderer-sass/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/Rawsec/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/noraj/.node-gyp/8.1.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/noraj/.node-gyp/8.1.2',
gyp info spawn args   '-Dnode_gyp_dir=/tmp/Rawsec/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/noraj/.node-gyp/8.1.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/tmp/Rawsec/node_modules/hexo-renderer-sass/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/noraj/.node-gyp/8.1.2
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/tmp/Rawsec/node_modules/hexo-renderer-sass/node_modules/node-sass/build'
  g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/noraj/.node-gyp/8.1.2/include/node -I/home/noraj/.node-gyp/8.1.2/src -I/home/noraj/.node-gyp/8.1.2/deps/uv/include -I/home/noraj/.node-gyp/8.1.2/deps/v8/include -I../../../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
In file included from ../src/binding.cpp:3:0:
../src/sass_context_wrapper.h:8:10: fatal error: sass/context.h: No such file or directory
 #include <sass/context.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [binding.target.mk:110: Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/tmp/Rawsec/node_modules/hexo-renderer-sass/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/tmp/Rawsec/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.9.33-1-MANJARO
gyp ERR! command "/usr/bin/node" "/tmp/Rawsec/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /tmp/Rawsec/node_modules/hexo-renderer-sass/node_modules/node-sass
gyp ERR! node -v v8.1.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/noraj/.npm/_logs/2017-06-25T18_14_44_215Z-debug.log
```

**Comment by noraj1337** [comment]
Old release, not compatible with Node 8. `node-sass` won't fix. https://github.com/sass/node-sass/issues/1932
Please use newer version.

**Comment by JLHwung** [comment]
Hi noraj1337,
AFAIK 0.3.2 will use node-sass 4.5.3, it should be compatible with Node 8. Which hexo-renderer-sass version do you use? You can check by
```
npm list --depth=0 | grep hexo-renderer-sass
```

If you are using an older version of hexo-renderer-sass, I recommend you to upgrade to the latest version. Thank you.

**Comment by noraj1337** [comment]
@JLHwung I use hexo-renderer-sass 0.3.2, yes you can see in my log it used node-sass@4.5.3 but also node-sass@3.13.1. It seems it's using both.

**Comment by JLHwung** [comment]
Hi noraj1337,

As I go through the log, it seems that you have run 
```
npm install hexo-render-sass --save
```
instead of 
```
npm install hexo-renderer-sass --save
```. 

As we are not affiliated with `hexo-render-sass`. Could you run `npm install hexo-renderer-sass --save` to see if this issues can be reproduced? Thank you.

**Comment by noraj1337** [comment]
I will this weekend when I'll have access to the VM.

**Comment by noraj1337** [comment]
I tried on another machine and `npm install hexo-renderer-sass` alone works but `npm install` on this package.json : 

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.3.7"
  },
  "dependencies": {
    "hexo": "^3.3.7",
    "hexo-deployer-git": "^0.3.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.0",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-json-content": "^3.0.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-i18n": "^0.2.1",
    "hexo-pagination": "^0.1.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-less": "^0.2.0",
    "hexo-renderer-markdown-it": "^3.4.1",
    "hexo-renderer-sass": "^0.3.2",
    "hexo-renderer-scss": "^1.0.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.2.1",
    "hexo-tag-bootstrap": "0.0.8"
  }
}
```

End with an error : 

```
gyp verb node dev dir /home/shark/.node-gyp/8.1.2
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/tmp/Rawsec/node_modules/hexo-renderer-scss/node_modules/node-sass/build'
  g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/shark/.node-gyp/8.1.2/include/node -I/home/shark/.node-gyp/8.1.2/src -I/home/shark/.node-gyp/8.1.2/deps/uv/include -I/home/shark/.node-gyp/8.1.2/deps/v8/include -I../../../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
In file included from ../src/binding.cpp:3:0:
../src/sass_context_wrapper.h:8:10: fatal error: sass/context.h: No such file or directory
 #include <sass/context.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [binding.target.mk:110: Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/tmp/Rawsec/node_modules/hexo-renderer-scss/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/tmp/Rawsec/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.9.34-1-MANJARO
gyp ERR! command "/usr/bin/node" "/tmp/Rawsec/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /tmp/Rawsec/node_modules/hexo-renderer-scss/node_modules/node-sass
gyp ERR! node -v v8.1.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
```

**Comment by noraj1337** [comment]
My bad, a mistake, I installed the broken `hexo-render-sass` instead of `hexo-renderer-sass`.

**Comment by JLHwung** [comment]
Hi,
I am glad that the issue is resolved. 

I would suggest convert your stylesheets to either sass or scss. Hero renderer sass supports either of them, but I don't think it works on a mixture of sass and scss.
