### ISSUE TITLE
Not able to make it work with Hexo 3.0

### ISSUE THREAD

**Issue by tiagorg** [knksmith57/hexo-renderer-sass#7]
Any thoughts?

```
➜  tiagorg.github.io-source git:(master) ✗ hexo clean
ERROR Plugin load failed: hexo-renderer-sass
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/tgarcia/Development/Personal/tiagorg.github.io-source/node_modules/hexo-renderer-sass/node_modules/node-sass/sass.js:11:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/tgarcia/Development/Personal/tiagorg.github.io-source/node_modules/hexo/lib/hexo/index.js:213:21)
    at /Users/tgarcia/Development/Personal/tiagorg.github.io-source/node_modules/hexo-renderer-sass/index.js:2:10
    at /Users/tgarcia/Development/Personal/tiagorg.github.io-source/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/Users/tgarcia/Development/Personal/tiagorg.github.io-source/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/tgarcia/Development/Personal/tiagorg.github.io-source/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/tgarcia/Development/Personal/tiagorg.github.io-source/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users/tgarcia/Development/Personal/tiagorg.github.io-source/node_modules/hexo/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/tgarcia/Development/Personal/tiagorg.github.io-source/node_modules/hexo/node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues (/Users/tgarcia/Development/Personal/tiagorg.github.io-source/node_modules/hexo/node_modules/bluebird/js/main/async.js:89:10)
    at Async.drainQueues (/Users/tgarcia/Development/Personal/tiagorg.github.io-source/node_modules/hexo/node_modules/bluebird/js/main/async.js:14:14)
    at process._tickCallback (node.js:355:11)
```

**Comment by imruxin** [comment]
Also the problem:

```
ERROR Plugin load failed: hexo-renderer-sass
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ruxin/website/ued/node_modules/hexo-renderer-sass/node_modules/node-sass/sass.js:11:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/ruxin/website/ued/node_modules/hexo/lib/hexo/index.js:213:21)
    at /Users/ruxin/website/ued/node_modules/hexo-renderer-sass/index.js:2:10
    at /Users/ruxin/website/ued/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/Users/ruxin/website/ued/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/ruxin/website/ued/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/ruxin/website/ued/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users/ruxin/website/ued/node_modules/hexo/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/ruxin/website/ued/node_modules/hexo/node_modules/bluebird/js/main/async.js:132:16)
    at Async._drainQueues (/Users/ruxin/website/ued/node_modules/hexo/node_modules/bluebird/js/main/async.js:142:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/ruxin/website/ued/node_modules/hexo/node_modules/bluebird/js/main/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by s10wen** [comment]
Getting the same, I'm using:
```
hexo: 3.0.1
os: Darwin 13.4.0 darwin x64
http_parser: 2.3
node: 0.12.2
v8: 3.28.73
uv: 1.4.2-node1
zlib: 1.2.8
modules: 14
openssl: 1.0.1m
```

**Comment by knksmith57** [comment]
Alright everybody-- raising this repo from the dead to get in some long overdue updates. I'm not running hexo as my blog platform anymore, so it's easy to forget that I need to keep this up to date. Really sorry about that.

With my updates and a clean install of hexo, I've got `hexo-renderer-sass@^0.1.0` working with the following versions:

```
blog ❱ hexo version
hexo: 3.0.1
os: Darwin 13.4.0 darwin x64
http_parser: 2.3
node: 0.12.2
v8: 3.28.73
uv: 1.4.2-node1
zlib: 1.2.8
modules: 14
openssl: 1.0.1m
```
and
```
blog ❱ hexo version
hexo: 3.0.1
os: Darwin 13.4.0 darwin x64
http_parser: 1.0
node: 0.10.38
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.36
zlib: 1.2.8
modules: 11
openssl: 1.0.1m
```

@tiagorg @imruxin @s10wen -- can y'all please run an `npm install --save hexo-renderer-sass@^0.1` and let me know what happens?

**Comment by s10wen** [comment]
Thanks @knksmith57 I can confirm that after running `npm install --save hexo-renderer-sass@^0.1` it is fixed, I'm running:

```
hexo: 3.0.1
os: Darwin 13.4.0 darwin x64
http_parser: 2.3
node: 0.12.0
v8: 3.28.73
uv: 1.0.2
zlib: 1.2.8
modules: 14
openssl: 1.0.1l
```

**Comment by knksmith57** [comment]
Awesome, going to close this out then.
